version: '3.4'

services:
  divartelegrambot:
    image: idebman/divartelegrambot
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - type: bind
        source: <PATH_TO_YOUR_DIR>/tokens.json
        target: /app/tokens.json
